import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

// components
import Header from "../components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/BlurFadeTransition";
import BackToTop from "@/components/BackToTop";
import CyberCursor from "@/components/CyberCursor";
import CyberBackground from "@/components/CyberBackground";

const jetbrainsMono = JetBrains_Mono({ 
  subsets: ["latin"], 
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable : '--font-jetbrainsMono' 
});

export const metadata = {
  title: "Gaurav Portfolio",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable}>
        <CyberBackground />
        <CyberCursor />
        <Header/ >
        <StairTransition/ >
        <BackToTop />
        <PageTransition>{ children }</PageTransition>
      </body>
    </html>
  );
}
